### ISSUE TITLE
Upgrade s6-overlay in base/Dockerfile

### ISSUE THREAD

**Issue by markkuriekkinen** [apluslms/service-base#1]
The currently used version of s6-overlay is about two years old. Would it make sense to upgrade it? Does the API change at all, in other words, does it require any changes in the code/scripts?

https://github.com/apluslms/service-base/blob/1.11/base/Dockerfile#L8

https://github.com/apluslms/service-base/blob/32f771bfe4d783b911fa61896524179bb89cde4f/base/Dockerfile#L8

**Comment by raphendyr** [comment]
Reading the s6-overlay release notes, it seems that the major version for skalib binaries has not changed, i.e., the tools some of our scripts use should have not changed.

Based on [CHANGELOG](https://github.com/just-containers/s6-overlay/blob/master/CHANGELOG.md), it seems that only major change is `with-contenv`. The change there seems to support more than 4k bytes of environment variables. Thus, I don't think there are any problems upgrading to a newer release. Test it out of course.

That said, I don't think there are major problems of not upgrading, as the tools are very low level and are used only in the development environment.

It's more important to update the underlying Linux distribution periodically.
